/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */
package org.opensearch.neuralsearch.jni;

import java.io.IOException;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

import org.apache.lucene.store.IndexOutput;
import org.opensearch.neuralsearch.sparse.common.SparseQueryResult;
import org.opensearch.neuralsearch.sparse.io.IndexOutputWrapper;
import org.opensearch.test.OpenSearchTestCase;

/**
 * Pins the Java side of the JNI boundary.
 * <p>
 * The native layer resolves these classes, methods, and signatures by string at
 * library load time (see jni/src/jni_util.cpp and jni/src/nsparse_stream_writer.cpp).
 * A rename, a signature change, or an extra field on SparseQueryResult therefore
 * breaks nothing at compile time and everything at runtime — with a cryptic
 * UnsatisfiedLinkError or "method not found" from JNI_OnLoad. These tests turn
 * each of those into a build failure instead.
 * <p>
 * Nothing here touches {@link NativeLibrary}'s static initializer, so the tests
 * run without the shared library present.
 */
public class NativeLibraryContractTests extends OpenSearchTestCase {

    /**
     * jni_util.cpp caches this constructor as "(IF)V". It is generated by Lombok's
     * {@code @Data}, so it is invisible in the source and easy to invalidate by
     * adding a field.
     */
    public void testSparseQueryResultHasTheConstructorJniCaches() throws Exception {
        // getConstructor (not getDeclaredConstructor) also asserts it is public,
        // which JNI NewObject requires.
        Constructor<SparseQueryResult> ctor = SparseQueryResult.class.getConstructor(int.class, float.class);

        SparseQueryResult result = ctor.newInstance(42, 0.75f);
        assertEquals("the first ctor arg must be the doc id", 42, result.getId());
        assertEquals("the second ctor arg must be the score", 0.75f, result.getScore(), 0.0f);
    }

    /**
     * Adding or removing a field shifts Lombok's generated constructor away from
     * (IF)V, and an extra overload would let that happen while the test above still
     * passes. Exactly one public constructor keeps the native signature unambiguous.
     */
    public void testSparseQueryResultHasExactlyOnePublicConstructor() {
        Constructor<?>[] ctors = SparseQueryResult.class.getConstructors();
        assertEquals("the native layer caches a single (IF)V constructor; found " + Arrays.toString(ctors), 1, ctors.length);
        assertArrayEquals(new Class<?>[] { int.class, float.class }, ctors[0].getParameterTypes());
    }

    /**
     * nsparse_stream_writer.cpp looks this up as writeBytes "([BII)V" on whatever
     * object writeIndex is handed.
     */
    public void testIndexOutputWrapperExposesWriteBytesForJni() throws Exception {
        Method writeBytes = IndexOutputWrapper.class.getMethod("writeBytes", byte[].class, int.class, int.class);
        assertTrue("writeBytes must be public for JNI CallVoidMethod", Modifier.isPublic(writeBytes.getModifiers()));
        assertEquals(void.class, writeBytes.getReturnType());
        assertTrue(
            "the native side relies on IOException surfacing as a pending Java exception",
            Arrays.asList(writeBytes.getExceptionTypes()).contains(IOException.class)
        );
    }

    /**
     * nsparse_stream_writer.cpp looks this up as getFilePointer "()J" and seeds its
     * alignment arithmetic from it. Renaming it, or changing the return type to int,
     * breaks every mmap-backed load with "array is misaligned for its element type".
     */
    public void testIndexOutputWrapperExposesGetFilePointerForJni() throws Exception {
        Method getFilePointer = IndexOutputWrapper.class.getMethod("getFilePointer");
        assertTrue("getFilePointer must be public for JNI CallLongMethod", Modifier.isPublic(getFilePointer.getModifiers()));
        assertEquals("the native side calls it as ()J", long.class, getFilePointer.getReturnType());
    }

    /** getFilePointer must report the wrapped IndexOutput's position, not a copy. */
    public void testIndexOutputWrapperReportsTheIndexOutputFilePointer() throws Exception {
        RecordingIndexOutput recording = new RecordingIndexOutput();
        recording.writeBytes(new byte[] { 1, 2, 3, 4, 5, 6, 7 }, 0, 7);
        try (IndexOutputWrapper wrapper = new IndexOutputWrapper(recording)) {
            assertEquals("a header already written must be visible to the native writer", 7L, wrapper.getFilePointer());
            wrapper.writeBytes(new byte[] { 8, 9 }, 0, 2);
            assertEquals(9L, wrapper.getFilePointer());
        }
    }

    /** writeBytes must reach the wrapped IndexOutput unchanged, offset included. */
    public void testIndexOutputWrapperForwardsBytesToIndexOutput() throws Exception {
        RecordingIndexOutput recording = new RecordingIndexOutput();
        try (IndexOutputWrapper wrapper = new IndexOutputWrapper(recording)) {
            wrapper.writeBytes(new byte[] { 1, 2, 3, 4, 5 }, 1, 3);
        }
        assertArrayEquals(new byte[] { 2, 3, 4 }, recording.written());
        assertTrue("closing the wrapper must close the IndexOutput", recording.closed);
    }

    /**
     * Every native method declared here must have a matching Java_..._ symbol in
     * the C++ sources. A declaration with no implementation only fails when the
     * method is first called, which for a codec path can be long after startup.
     */
    public void testEveryDeclaredNativeMethodHasAnExportedSymbol() throws Exception {
        String nsparseService = readProjectFile("jni/src/org_opensearch_neuralsearch_jni_NsparseService.cpp");

        List<String> nativeMethods = declaredNativeMethodNames().stream().sorted().collect(Collectors.toList());
        assertFalse("expected NativeLibrary to declare native methods", nativeMethods.isEmpty());

        for (String method : nativeMethods) {
            String symbol = "Java_org_opensearch_neuralsearch_jni_NativeLibrary_" + method;
            assertTrue(
                "no native implementation exported for NativeLibrary." + method + " (expected " + symbol + ")",
                nsparseService.contains(symbol)
            );
        }
    }

    /**
     * The reverse direction: an exported symbol with no Java declaration can never
     * be bound and is dead weight in the shared library.
     */
    public void testEveryExportedSymbolHasADeclaredNativeMethod() throws Exception {
        String nsparseService = readProjectFile("jni/src/org_opensearch_neuralsearch_jni_NsparseService.cpp");
        Set<String> declared = declaredNativeMethodNames();

        java.util.regex.Matcher matcher = java.util.regex.Pattern.compile("Java_org_opensearch_neuralsearch_jni_(\\w+?)_(\\w+)\\s*\\(")
            .matcher(nsparseService);
        while (matcher.find()) {
            String owningClass = matcher.group(1);
            String method = matcher.group(2);
            assertEquals("exported symbol targets a class other than NativeLibrary: " + matcher.group(), "NativeLibrary", owningClass);
            assertTrue("exported symbol " + matcher.group() + " has no matching native method on NativeLibrary", declared.contains(method));
        }
    }

    /** The names are the library base name plus each suffix, in order. */
    public void testCandidateNamesAreOrderedMostSpecificFirst() {
        List<String> all = NativeLibraryCandidates.allCandidates();
        assertEquals(NativeLibraryCandidates.SIMD_SUFFIXES.size(), all.size());
        for (int i = 0; i < all.size(); i++) {
            assertEquals(NativeLibraryCandidates.LIBRARY_NAME + NativeLibraryCandidates.SIMD_SUFFIXES.get(i), all.get(i));
        }
        assertEquals("the generic build must be tried last", NativeLibraryCandidates.LIBRARY_NAME, all.get(all.size() - 1));
    }

    /**
     * A distribution build ships every variant, so what is on disk no longer proves
     * the CPU can run it — candidates() must drop the ones it cannot, keep the rest
     * in the same order, and always end with the generic build.
     */
    public void testCandidatesAreTheSupportedSubsetInOrder() {
        List<String> supported = NativeLibraryCandidates.candidates();
        List<String> all = NativeLibraryCandidates.allCandidates();

        assertEquals("the generic build is always a candidate", NativeLibraryCandidates.LIBRARY_NAME, supported.get(supported.size() - 1));
        assertTrue("candidates() must be a subset of the names a build can produce", all.containsAll(supported));
        assertEquals(
            "candidates() must preserve the most-specific-first order",
            all.stream().filter(supported::contains).collect(Collectors.toList()),
            supported
        );
    }

    /**
     * Every variant cmake can build needs a CPU check paired with it. A suffix without
     * one would be loaded on any host that happens to have the file, which for a
     * distribution artifact means SIGILL on the first vectorized call rather than a
     * failed load.
     */
    public void testEveryCmakeVariantIsGatedOnACpuCheck() throws Exception {
        Set<String> cmakeSuffixes = simdSuffixesInCmake();
        List<String> gated = NativeLibraryCandidates.SIMD_SUFFIXES;
        for (String suffix : cmakeSuffixes) {
            assertTrue(
                "init-nsparse.cmake can build " + suffix + " but NativeLibraryCandidates does not pair it with a CPU check",
                gated.contains(suffix)
            );
        }
        // Only the generic build may be unconditional.
        assertEquals("", gated.get(gated.size() - 1));
    }

    /**
     * The SIMD suffixes init-nsparse.cmake can bake into the library filename. Parsed
     * from the cmake source because the two sides have no shared source of truth.
     */
    private Set<String> simdSuffixesInCmake() throws IOException {
        String cmake = readProjectFile("jni/cmake/init-nsparse.cmake");
        Matcher matcher = Pattern.compile("string\\(PREPEND LIB_EXT \"(_\\w+)\"\\)").matcher(cmake);
        Set<String> suffixes = new HashSet<>();
        while (matcher.find()) {
            suffixes.add(matcher.group(1));
        }
        assertFalse("expected init-nsparse.cmake to append at least one SIMD suffix", suffixes.isEmpty());
        return suffixes;
    }

    /**
     * The native methods NativeLibrary itself declares. Filtered by declaring class
     * because getMethods() also reports java.lang.Object's native members.
     */
    private Set<String> declaredNativeMethodNames() {
        return Arrays.stream(NativeLibrary.class.getMethods())
            .filter(m -> m.getDeclaringClass() == NativeLibrary.class)
            .filter(m -> Modifier.isNative(m.getModifiers()))
            .map(Method::getName)
            .collect(Collectors.toSet());
    }

    private String readProjectFile(String relativePath) throws IOException {
        // `test` runs with project.root set by build.gradle; fall back to the CWD,
        // which gradle sets to the project directory.
        String root = System.getProperty("project.root", "");
        Path path = root.isEmpty() ? Path.of(relativePath) : Path.of(root, relativePath);
        assertTrue("expected to find " + path + " — is project.root set correctly?", Files.exists(path));
        return Files.readString(path);
    }

    /** Minimal IndexOutput that records what was written. */
    private static final class RecordingIndexOutput extends IndexOutput {
        private final java.io.ByteArrayOutputStream buffer = new java.io.ByteArrayOutputStream();
        private boolean closed = false;

        RecordingIndexOutput() {
            super("recording", "recording");
        }

        byte[] written() {
            return buffer.toByteArray();
        }

        @Override
        public void writeByte(byte b) {
            buffer.write(b);
        }

        @Override
        public void writeBytes(byte[] b, int offset, int length) {
            buffer.write(b, offset, length);
        }

        @Override
        public void close() {
            closed = true;
        }

        @Override
        public long getFilePointer() {
            return buffer.size();
        }

        @Override
        public long getChecksum() {
            return 0L;
        }
    }
}
