/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */
package org.opensearch.neuralsearch.transport;

import lombok.Getter;
import org.opensearch.action.support.nodes.BaseNodeResponse;
import org.opensearch.cluster.node.DiscoveryNode;
import org.opensearch.core.common.io.stream.StreamInput;
import org.opensearch.core.common.io.stream.StreamOutput;
import org.opensearch.core.xcontent.ToXContentFragment;
import org.opensearch.core.xcontent.XContentBuilder;
import org.opensearch.neuralsearch.stats.events.TimestampedEventStatSnapshot;
import org.opensearch.neuralsearch.stats.events.EventStatName;

import java.io.IOException;
import java.util.Map;

/**
 * NeuralStatsNodeResponse represents the responses generated by an individual node
 */
public class NeuralStatsNodeResponse extends BaseNodeResponse implements ToXContentFragment {
    @Getter
    private Map<EventStatName, TimestampedEventStatSnapshot> stats;

    /**
     * Constructor
     *
     * @param in  stream
     * @throws IOException in case of I/O errors
     */
    public NeuralStatsNodeResponse(StreamInput in) throws IOException {
        super(in);
        this.stats = in.readMap(input -> input.readEnum(EventStatName.class), TimestampedEventStatSnapshot::new);
    }

    /**
     * Constructor
     *
     * @param node node
     * @param stats mapping of stat name to value
     */
    public NeuralStatsNodeResponse(DiscoveryNode node, Map<EventStatName, TimestampedEventStatSnapshot> stats) {
        super(node);
        this.stats = stats;
    }

    /**
     * Creates a new NeuralStatsNodeResponse object and reads in the stats from an input stream
     *
     * @param in StreamInput to read from
     * @return NeuralStatsNodeResponse object corresponding to the input stream
     * @throws IOException throws an IO exception if the StreamInput cannot be read from
     */
    public static NeuralStatsNodeResponse readStats(StreamInput in) throws IOException {
        NeuralStatsNodeResponse neuralStats = new NeuralStatsNodeResponse(in);
        return neuralStats;
    }

    @Override
    public void writeTo(StreamOutput out) throws IOException {
        super.writeTo(out);
        out.writeMap(stats, StreamOutput::writeEnum, (output, eventStatData) -> eventStatData.writeTo(output));
    }

    /**
     * Converts statsMap to xContent
     *
     * @param builder XContentBuilder
     * @param params Params
     * @return XContentBuilder
     * @throws IOException thrown by builder for invalid field
     */
    public XContentBuilder toXContent(XContentBuilder builder, Params params) throws IOException {
        for (Map.Entry<EventStatName, TimestampedEventStatSnapshot> entry : stats.entrySet()) {
            EventStatName stat = entry.getKey();
            builder.field(stat.getFullPath(), entry.getValue().getValue());
        }
        return builder;
    }
}
