/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */
package org.opensearch.neuralsearch.transport;

import lombok.Getter;
import org.opensearch.action.support.nodes.BaseNodeResponse;
import org.opensearch.cluster.node.DiscoveryNode;
import org.opensearch.core.common.io.stream.StreamInput;
import org.opensearch.core.common.io.stream.StreamOutput;
import org.opensearch.core.xcontent.ToXContentFragment;
import org.opensearch.core.xcontent.XContentBuilder;

import java.io.IOException;
import java.util.Map;
import java.util.TreeMap;

/**
 * NeuralStatsNodeResponse represents the responses generated by an individual node
 */
public class NeuralStatsNodeResponse extends BaseNodeResponse implements ToXContentFragment {

    @Getter
    private Map<String, Long> statsMap;

    /**
     * Constructor
     *
     * @param in  stream
     * @throws IOException in case of I/O errors
     */
    public NeuralStatsNodeResponse(StreamInput in) throws IOException {
        super(in);
        this.statsMap = new TreeMap<>(in.readMap(StreamInput::readString, StreamInput::readLong));
    }

    /**
     * Constructor
     *
     * @param node node
     * @param statsToValues mapping of stat name to value
     */
    public NeuralStatsNodeResponse(DiscoveryNode node, Map<String, Long> statsToValues) {
        super(node);
        this.statsMap = new TreeMap<>(statsToValues);
    }

    /**
     * Creates a new NeuralStatsNodeResponse object and reads in the stats from an input stream
     *
     * @param in StreamInput to read from
     * @return NeuralStatsNodeResponse object corresponding to the input stream
     * @throws IOException throws an IO exception if the StreamInput cannot be read from
     */
    public static NeuralStatsNodeResponse readStats(StreamInput in) throws IOException {
        NeuralStatsNodeResponse neuralStats = new NeuralStatsNodeResponse(in);
        return neuralStats;
    }

    @Override
    public void writeTo(StreamOutput out) throws IOException {
        super.writeTo(out);
        out.writeMap(statsMap, StreamOutput::writeString, StreamOutput::writeLong);
    }

    /**
     * Converts statsMap to xContent
     *
     * @param builder XContentBuilder
     * @param params Params
     * @return XContentBuilder
     * @throws IOException thrown by builder for invalid field
     */
    public XContentBuilder toXContent(XContentBuilder builder, Params params) throws IOException {
        for (String stat : statsMap.keySet()) {
            builder.field(stat, statsMap.get(stat));
        }
        return builder;
    }
}
